In [2]:
import fsm
from fsm.sparse.spartype import *
import numpy as np
import numba as nb
import random_gen

[[0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]]
[1.24548529 1.89045654 3.84037644 2.04071459 4.62537818 2.77903261
 2.92246031 2.39819627 1.07870283 1.56135397]
[1.24548529 1.89045654 3.84037644 2.04071459 4.62537818 2.77903261
 2.92246031 2.39819627 1.07870283 1.56135397]


In [9]:
rows_array

array([ 3,  1,  4,  3,  5,  3,  6,  0,  7,  2,  7,  1,  8,  0, 11,  3, 11,
       11,  1, 15, 16,  3, 17, 17], dtype=uint32)

In [4]:
n = np.asfortranarray(np.random.rand(5)).shape[0]

In [5]:
n = 5

In [6]:
B = fsm.sparse.fcsr.fcsr_constructor(5)

In [13]:
B.b_decomp[0].dot1d(np.asfortranarray(np.random.rand(4)))

array([0.56775786, 0.26561674, 0.19518608, 0.53564341])